robots:
  -
    id: 1
    name: 'Virtual Machine'
    enabled: true
    recording: false
    defaultAddress: 'ethernet'
    addresses:
      ethernet:
        host: 127.0.0.1
        port: 12000
  -
    id: 2
    name: 'Robot Simulator'
    enabled: true
    recording: false
    defaultAddress: 'ethernet'
    addresses:
      ethernet:
        host: 127.0.0.1
        port: 14000
  -
    id: 3
    name: 'Robot #1'
    enabled: true
    recording: false
    defaultAddress: 'wifi'
    addresses:
      wifi:
        host: 10.1.1.1
        port: 12000
      ethernet:
        host: 10.1.2.1
        port: 12000
  -
    id: 4
    name: 'Robot #2'
    enabled: true
    recording: false
    defaultAddress: 'wifi'
    addresses:
      wifi:
        host: 10.1.1.2
        port: 12000
      ethernet:
        host: 10.1.2.2
        port: 12000
  -
    id: 5
    name: 'Robot #3'
    enabled: true
    recording: false
    defaultAddress: 'wifi'
    addresses:
      wifi:
        host: 10.1.1.3
        port: 12000
      ethernet:
        host: 10.1.2.3
        port: 12000
  -
    id: 6
    name: 'Robot #4'
    enabled: true
    recording: false
    defaultAddress: 'wifi'
    addresses:
      wifi:
        host: 10.1.1.4
        port: 12000
      ethernet:
        host: 10.1.2.4
        port: 12000
  -
    id: 7
    name: 'Robot #5'
    enabled: true
    recording: false
    defaultAddress: 'wifi'
    addresses:
      wifi:
        host: 10.1.1.5
        port: 12000
      ethernet:
        host: 10.1.2.5
        port: 12000
  -
    id: 8
    name: 'Robot #6'
    enabled: true
    recording: false
    defaultAddress: 'wifi'
    addresses:
      wifi:
        host: 10.1.1.6
        port: 12000
      ethernet:
        host: 10.1.2.6
        port: 12000
  -
    id: 9
    name: 'Robot #7'
    enabled: true
    recording: false
    defaultAddress: 'wifi'
    addresses:
      wifi:
        host: 10.1.1.7
        port: 12000
      ethernet:
        host: 10.1.2.7
        port: 12000
